#!/bin/bash

#Start Sxhkd
sxhkd -c $HOME/.config/berry/sxhkdrc &
# Set decoration geometry
berryc border_width       0
berryc inner_border_width 3
berryc title_height 20
#berryc top_gap         30
berryc edge_gap	34 20 25 25

# Set decoration colors
berryc focus_color         292D3E
berryc unfocus_color       292D3E
berryc inner_focus_color   FFCB6B
berryc inner_unfocus_color 565679
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Fira code-9"

# autostart options
feh --bg-scale $HOME/Pictures/forest.jpg
dunst &
picom --config $HOME/.config/berry/picom.conf &

#bar
sh ~/.config/berry/lemonbar.sh | lemonbar -g 1550x20+25+10 -f "Fira code:size=10" -p &
