#!/bin/bash

#Start Sxhkd
sxhkd -c $HOME/.config/berry/sxhkdrc &
# Set decoration geometry
berryc border_width       0
berryc inner_border_width 4
berryc title_height 18
#berryc top_gap         30
berryc edge_gap	35 10 10 10

# Set decoration colors

#not used
berryc focus_color         292D3E
berryc unfocus_color       292D3E
#main used
berryc inner_focus_color   282828
berryc inner_unfocus_color 1d2021 
berryc text_focus_color    ebdbb2
berryc text_unfocus_color  ebdbb2

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Fira code-10"

# autostart options
feh --bg-scale $HOME/.config/berry/forest.jpg
dunst &
picom --config $HOME/.config/berry/picom.conf &

#bar
polybar stardust &
